# Generated by Django 2.0.6 on 2018-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
